#Experiment config file
# Basic file for parameters of the experiment
# All delays in seconds

n_trials: 2

# the delay before starting and after ending the experiment (black square comes on at half of this time)
experiment_delay: 5
stim_length: 2.5
inter_trial_delay: 2.5

#Parameters of visual stimuli

# 4 orientation gratings
grating_sf: 0.08
grating_position: [0, 0]
grating_orientations: [0, 45, 90]
grating_phases_range: [0, 1]
grating_size: [60, 60]
grating_mask: 'gauss'

