#Experiment config file
# Basic file for parameters of the experiment
# All delays in seconds
name: "DynamicBatteryTuning"

n_trials: 200

# the delay before starting and after ending the experiment (black square comes on at half of this time)
experiment_delay: 1
# stim on length
stim_length: 0.25

# stim off length (iti)
inter_trial_delay: 0.75

#Parameters of visual stimuli

# As per our original rationale:
# spatial frequency, orientation, stimulus size
# phase alternates at the half period of the stimulus
grating_position: [0, 0]
grating_orientations: [0]
grating_sfs: [0.0222]
grating_sizes: [100] # assumes sizes equal along x and y axes. 


give_blanks: False


grating_mask: 'raisedCos'


trial_params_columns: ["trial_number", "clock_time", "orientation", "sf", "size", "stim_info_str"]
