#Configuration section for the monitor being used
# By default monitor is full screen TODO is this ok?
monitor_name: 'FED_IIYAMA_23'
monitor_width_pixels: 1920
monitor_height_pixels: 1080
monitor_width_cm: 52.2
screen_id: 0
viewing_distance_cm: 25
monitor_gamma: 1
