#Configuration section for the monitor being used
# By default monitor is full screen TODO is this ok?
monitor_name: 'FED_IIYAMA_23'
monitor_width_pixels: 1920
monitor_height_pixels: 1080
monitor_width_cm: 52.2
screen_id: 0
viewing_distance_cm: 30
monitor_gamma: 1


# TODO need to add square settings
# UNITS in pixels
# [width, size
square_size: [600, 600]
square_position: [-960 , -540] # find a nicer way to specify, but this is basically -(resolution/2) for left corner


# color units are 0->1 (1 is max white)
square_color_off: [-1]
square_color_on: [1]
