#Configuration section for the monitor being used
# By default monitor is full screen TODO is this ok?
monitor_name: 'FED_IIYAMA_23'
monitor_width_pixels: 1920
monitor_height_pixels: 1080
monitor_width_cm: 52.2
screen_id: 1
viewing_distance_cm: 25
monitor_gamma: 1


# TODO need to add square settings
square_size: [100, 100]
square_location: [0, 0]
square_color_off: [0]
square_color_on: [255]
