#Configuration section for the monitor being used
# By default monitor is full screen TODO is this ok?
monitor_name: 'FED_IIYAMA_23'
#monitor_width_pixels: 1920
#monitor_height_pixels: 1080
#monitor_width_cm: 52.2

use_spherical_warp: False

monitor_width_pixels: 1920
monitor_height_pixels: 1080
monitor_width_cm: 52.5
monitor_height_cm: 29.5
screen_id: 1
viewing_distance_cm: 15
monitor_gamma: 1
monitor_refresh_rate: 60

#monitor_gamma_lut: '/home/k1n4s3/LABSERVER6/Personal/Federico/GitRepos/monitor-calibrations/IIYAMA_Prolite_LE4041UHS.npy'

######## Only Used for Retinotopy Experiments
# Monitor extra settings
mon_center_coordinates: [0., 60.]
mon_downsample_rate: 5
#mon_gamma: 2

# indicator settings
ind_width_cm: 3.
ind_height_cm: 3.
ind_position: 'southeast'
ind_is_sync: true
ind_freq: 1.

# TODO need to add square settings
# UNITS in pixels
# [width, size
square_size: [200, 200]
square_position: [-960 , -540] # find a nicer way to specify, but this is basically -(resolution/2) for left corner
#square_position: [-800 , -450] # find a nicer way to specify, but this is basically -(resolution/2) for left corner

# color units are 0->1 (1 is max white)
square_color_off: [-1]
square_color_on: [1]

