LABSERVER_DIR_WIN: "\\\\files.ubc.ca\\team\\BNRC\\NINC\\federico\\MurphyLab\\simple-vs-debug"
# LABSERVER_DIR_LIN: "/home/k1n4s3/LABSERVER6/MOUSE/FB_2P_Analysis/2p_TEX/"
#LABSERVER_DIR_LIN: "/home/k1n4s3/TESTS/"
#LABSERVER_DIR_LIN: "/home/manatee/TESTS/"
LABSERVER_DIR_LIN: "/home/federico/TESTS/"
#LABSERVER_DIR_LIN: "/home/rh0d0ps1n3/TESTS/"

dirs_to_make: ["VSLogs", "2p", "BT", "ET", "Segmented", "Figures"]

# Folder where the DAQ data and the VS trials param data is saved
log_folder: "VSLogs"
