#Experiment config file
# Basic file for parameters of the experiment
# All delays in seconds
name: "TextureExperimentFB_MultiTime"

# array containing all the images to display, must have shape (n_images, im_y, im_x)
images_filename: "/home/k1n4s3/LABSERVER6/Personal/Federico/TextureProject/fb_stimuli_210205.npy"
#images_filename: "/home/rh0d0ps1n3/Documents/RIKEN/LABSERVER6/Personal/Federico/TextureProject/fb_stimuli_210205.npy"
#images_filename: "//NCB-LABSERVER6/data/Personal/Federico/TextureProject/fb_stimuli_200616.npy"

# the file that contains where each image comes from, type, family, subfamily, full name, indexing must be identical to images_filename
images_properties_filename: "/home/k1n4s3/LABSERVER6/Personal/Federico/TextureProject/fb_stim-props_210205.h5"
#images_properties_filename: "/home/rh0d0ps1n3/Documents/RIKEN/LABSERVER6/Personal/Federico/TextureProject/fb_stim-props_210205.h5"
#images_properties_filename: "//NCB-LABSERVER6/data/Personal/Federico/TextureProject/fb_stim-props_200616.h5"

#in addition, the first half of the images array must be of one type and the second half of the other type. 

# Custom vignette
#vignette_filename: "/home/k1n4s3/LABSERVER6/Personal/Federico/TextureProject/vignette.npy"
vignette_filename: "/home/rh0d0ps1n3/Documents/RIKEN/LABSERVER6/Personal/Federico/TextureProject/vignette.npy"
#vignette_filename: "//NCB-LABSERVER6/data/Personal/Federico/TextureProject/vignette.npy"


chosen_stim_types: ['texture', 'low-complexity']
chosen_families: ['scales', 'rocks', 'noodles', 'beans', 'worms', 'spikes', 'rocksFB', 'plantsFB']
give_blanks: False



# of texture and blanks how many images of each to display?
# we will show the same 
n_stims_per_condition: 4 # 


# the delay before starting and after ending the experiment (black square comes on at half of this time)
experiment_delay: 8
image_repeat_times: 1 # n times to repeat image, the last period does not have an image off period and goes into ITI
image_on_periods: [0.25, 0.5, 1.0] 
image_off_period: 0.0
inter_trial_delay: 1.0

#Parameters of visual stimuli
image_position: [0, 0]
image_sizes: [100]
image_mask: "raisedCos"
image_mask_sd: None



trial_params_columns: ["trial_number", "clock_time", "index", "stim_info_dict"]
