#Experiment config file
# Basic file for parameters of the experiment
# All delays in seconds
name: "TextureExperimentFB"

# array containing all the images to display, must have shape (n_images, im_y, im_x)
images_filename: "/home/k1n4s3/LABSERVER6/Personal/Federico/TextureProject/my_picked_images.npy"
# the file that contains where each image comes from, type, family, subfamily, full name, indexing must be identical to images_filename
images_properties_filename: "/home/k1n4s3/LABSERVER6/Personal/Federico/TextureProject/my_picked_image_properties.h5"
#in addition, the first half of the images array must be of one type and the second half of the other type. 

chosen_families: ['scales', 'worms', 'leopard', 'clouds']
chosen_subfamilies: ['pool4', 'pool2']


# number of times to show each image
n_trials: 5
give_blanks: True
# of texture and blanks how many images of each to display?
# we will show the same 
n_images_per_class_to_display: 5




# the delay before starting and after ending the experiment (black square comes on at half of this time)
experiment_delay: 3
image_period: 0.75
inter_trial_delay: 2.5

#Parameters of visual stimuli

# 4 moving orientation gratings
image_position: [0, 0]
image_size: [60, 60]
image_mask: 'gauss'
image_mask_sd: 2



trial_params_columns: ["trial_number", "clock_time", "orientation", "stim_info_str"]
